import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { OrganizationSwitcher, SignedIn, SignedOut, UserButton, clerkClient, useAuth } from '@clerk/nextjs'
import { SignIn } from '@clerk/clerk-react'
import { GetServerSideProps } from 'next'
import { buildClerkProps, getAuth } from '@clerk/nextjs/server'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps: GetServerSideProps = async ctx => {
  const { userId } = getAuth(ctx.req)
  const user = userId ? await clerkClient.users.getUser(userId) : undefined;

  return { props: { ...buildClerkProps(ctx.req, { user }) } }
}

export default function Home() {
  const auth = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <p>Login status: {"" + (auth.isSignedIn || false)}</p>
        <SignedOut>
          <SignIn />
        </SignedOut>
        <SignedIn>
          <div>
            <UserButton />
            <OrganizationSwitcher />
          </div>
        </SignedIn>
      </main>
    </>
  )
}
